### ISSUE TITLE
[Bug] Default password in logs does not match auth credentials

### ISSUE THREAD

**Issue by nielsvermaut** [conceptant/bind9-namedmanager#1]
Hi!

I've tried to use the docker image that you guys provided. Everything booted up nice, and when I was confronted with the login screen, I referred to the stdout logs via ```docker logs```. The given credentials there don't seem to work. 

I tried referring to the README, which states that you can rebuild the image with custom passwords, but I'm not really too sure on how to do that, since the Dockerfile doesn't really imports any mysql dumps.

Any clue on how I could tackle this?

Thanks!

**Comment by d0ng13** [comment]
This password 'setup 123' has an otiose space. 'setup/setup123' is ok.
